### ISSUE TITLE
Demo link in README.md is possibly broken.

### ISSUE THREAD

**Issue by johan718** [tdooner/irma-response-bot-api#19]
When I click on:

[https://us-central1-irma-response-bot.cloudfunctions.net/sheltersByZip?zip=34972]( https://us-central1-irma-response-bot.cloudfunctions.net/sheltersByZip?zip=34972)

The page I'm taken to a page that only displays the following message:

`Invalid request`

I'm using **Google Chrome Version 60.0.3112.113 (Official Build) (64-bit)** on **Windows 7 Pro SP1**.

**Comment by johan718** [comment]
**Google Chrome Version 61.0.3163.79 (Official Build) (64-bit)** also shows the same error message.

**Comment by tdooner** [comment]
Good catch, the URL changed last night. It should now be:

https://us-central1-irma-response-bot.cloudfunctions.net/sheltersByZip?testAction=lookup-shelter&zip=33144&lang=en

**Comment by johan718** [comment]
Nice...works on my iPhone with safari.
