### ISSUE TITLE
ETL the code results in an API.AI compatible format

### ISSUE THREAD

**Issue by ErnieAtLYD** [tdooner/irma-response-bot-api#2]
Per @tdooner on the irma-response Slack:

"I made some headway on the API which translates the Irma API into a format that a chatbot can use. It's pretty simple so far, but it still needs a bit of work:
https://github.com/tdooner/irma-response-bot-api/commit/392f91fcb8932e67d6e0c19f149ce37cc1a2f543

For example, check out the results here:
https://us-central1-irma-response-bot.cloudfunctions.net/sheltersByZip?zip=34972

The code now just needs to return a result in the format that API.AI will be able to accept. If you know Node, this is something you could help with!"

**Comment by tdooner** [comment]
Sync up with @tabinfl in the irma-response slack org before starting this.

**Comment by tdooner** [comment]
I think it works now.
